'use client';

import { motion, useScroll, useTransform } from 'framer-motion';
import { useRef } from 'react';
import { Cpu, Globe2, Layers, Sparkles } from 'lucide-react';

// Parallax sticky-scroll section showcasing 4D/cinematic engineering
const HIGHLIGHTS = [
  {
    icon: Layers,
    title: '4D Hyperdimensional Design',
    description: 'We think beyond flat screens — tesseracts, projected geometries, and time-based interactions that feel alive.',
  },
  {
    icon: Cpu,
    title: 'GPU-Accelerated Everything',
    description: 'WebGL, compute shaders, and instanced rendering — we squeeze every drop of performance from the GPU.',
  },
  {
    icon: Globe2,
    title: 'Real-Time Global Illumination',
    description: 'Dynamic lighting, reflections, and shadows that respond to user input — cinematic in the browser.',
  },
  {
    icon: Sparkles,
    title: 'AI-Generated Assets',
    description: 'Every visual on this site was generated by AI. So is the logo. So is the conversation.',
  },
];

export default function Parallax4DSection() {
  const ref = useRef<HTMLDivElement>(null);
  const { scrollYProgress } = useScroll({
    target: ref,
    offset: ['start end', 'end start'],
  });

  // Parallax transforms
  const imgY = useTransform(scrollYProgress, [0, 1], ['-15%', '15%']);
  const imgScale = useTransform(scrollYProgress, [0, 0.5, 1], [1.1, 1, 1.1]);
  const textY = useTransform(scrollYProgress, [0, 1], ['40%', '-40%']);
  const rotate = useTransform(scrollYProgress, [0, 1], [-8, 8]);

  return (
    <section ref={ref} className="relative py-24 md:py-40 overflow-hidden">
      <div className="absolute inset-0 grid-bg opacity-10 pointer-events-none" />

      <div className="container mx-auto px-4 sm:px-6 relative z-10">
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-12 lg:gap-16 items-center">
          {/* Left: parallax image */}
          <div className="relative order-2 lg:order-1">
            <motion.div
              style={{ y: imgY, scale: imgScale, rotate }}
              className="relative rounded-3xl overflow-hidden glass-strong p-2"
            >
              <div className="relative rounded-2xl overflow-hidden aspect-square">
                {/* eslint-disable-next-line @next/next/no-img-element */}
                <img
                  src="/ai-images/4d-shapes.png"
                  alt="4D hyperdimensional render"
                  className="w-full h-full object-cover"
                />
                <div className="absolute inset-0 bg-gradient-to-t from-background/40 to-transparent" />
              </div>
            </motion.div>

            {/* Floating accent badges */}
            <motion.div
              animate={{ y: [0, -12, 0] }}
              transition={{ duration: 4, repeat: Infinity }}
              className="absolute -top-4 -left-4 glass-strong rounded-2xl px-4 py-2 border border-white/10 glow-cyan"
            >
              <div className="text-xs uppercase tracking-wider text-muted-foreground">Render Engine</div>
              <div className="font-[family-name:var(--font-syne)] font-bold text-sm gradient-text">WebGL · GLSL</div>
            </motion.div>
            <motion.div
              animate={{ y: [0, 12, 0] }}
              transition={{ duration: 5, repeat: Infinity, delay: 1 }}
              className="absolute -bottom-4 -right-4 glass-strong rounded-2xl px-4 py-2 border border-white/10 glow-violet"
            >
              <div className="text-xs uppercase tracking-wider text-muted-foreground">Dimension</div>
              <div className="font-[family-name:var(--font-syne)] font-bold text-sm gradient-text">4D · Cinematic</div>
            </motion.div>
          </div>

          {/* Right: sticky text content */}
          <motion.div style={{ y: textY }} className="order-1 lg:order-2">
            <motion.span
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              className="inline-flex items-center gap-2 px-3 py-1 rounded-full text-xs font-medium uppercase tracking-[0.2em] glass text-cyan-300 mb-5"
            >
              <span className="w-1.5 h-1.5 rounded-full bg-cyan-400" />
              Beyond 3D
            </motion.span>
            <motion.h2
              initial={{ opacity: 0, y: 30, filter: 'blur(8px)' }}
              whileInView={{ opacity: 1, y: 0, filter: 'blur(0px)' }}
              viewport={{ once: true }}
              transition={{ duration: 0.8 }}
              className="font-[family-name:var(--font-syne)] text-4xl sm:text-5xl md:text-6xl font-extrabold tracking-tight mb-6"
            >
              We Engineer in <span className="gradient-text-animated">4 Dimensions</span>
            </motion.h2>
            <p className="text-base sm:text-lg text-muted-foreground leading-relaxed mb-8">
              Most agencies stop at 2D. We add depth (3D), then time (4D) — creating experiences that
              evolve as users move, scroll, and interact. This is the cinematic web.
            </p>

            <div className="space-y-4">
              {HIGHLIGHTS.map((h, i) => (
                <motion.div
                  key={h.title}
                  initial={{ opacity: 0, x: 30 }}
                  whileInView={{ opacity: 1, x: 0 }}
                  viewport={{ once: true }}
                  transition={{ delay: i * 0.12, duration: 0.6 }}
                  className="flex items-start gap-4 group"
                >
                  <div className="w-11 h-11 rounded-xl bg-gradient-to-br from-violet-500/20 to-cyan-400/20 border border-white/10 flex items-center justify-center flex-shrink-0 group-hover:from-violet-500 group-hover:to-cyan-400 transition-all">
                    <h.icon className="w-5 h-5 text-cyan-300 group-hover:text-white transition-colors" />
                  </div>
                  <div>
                    <h3 className="font-[family-name:var(--font-syne)] font-bold text-base sm:text-lg mb-1">
                      {h.title}
                    </h3>
                    <p className="text-sm text-muted-foreground leading-relaxed">{h.description}</p>
                  </div>
                </motion.div>
              ))}
            </div>
          </motion.div>
        </div>
      </div>
    </section>
  );
}
